# .github/workflows/create-Debian-executable.yml

name: Create Debian Installer (DEB)

on:
  push:
    branches: [main]

jobs:
  build-Debian:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install required system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fakeroot dpkg-dev libfreetype6-dev libasound2-dev libx11-dev libxext-dev libxrender-dev libxtst-dev libxi-dev

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests

    - name: Package with jpackage into a DEB installer
      run: |
        jpackage \
          --type deb \
          --name "ByBo" \
          --app-version 1.0.0 \
          --vendor "phkaiser13" \
          --input "bybo-app/target/" \
          --main-jar "bybo-app-1.0.0-SNAPSHOT.jar" \
          --main-class "br.com.phkaiser.bybo.app.Launcher" \
          --icon "bybo-app/src/main/resources/br/com/phkaiser/bybo/app/ui/appicons/ByBo.png" \
          --linux-shortcut \
          --linux-menu-group "Utility"

    - name: Upload Debian Installer (DEB)
      uses: actions/upload-artifact@v4
      with:
        name: ByBo-Debian-Installer-DEB
        path: ByBo-1.0.0.deb
