# .github/workflows/release.yml

name: Create Release

on:
  push:
    tags:
      - '*' # Aciona para qualquer tag, sem o 'v'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up virtual framebuffer on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Build with Maven
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn -B verify --file pom.xml

      - name: Package Windows MSI
        if: runner.os == 'Windows'
        run: |
          mvn jpackage:jpackage \
            -DappVersion=${GITHUB_REF_NAME} \
            -DinstallerType=msi

      - name: Package macOS DMG
        if: runner.os == 'macOS'
        run: |
          mvn jpackage:jpackage \
            -DappVersion=${GITHUB_REF_NAME} \
            -DinstallerType=dmg

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Assets to Release
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: target/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
