# .github/workflows/release.yml

name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            installer_type: msi
            file_extension: msi
          - os: macos-latest
            installer_type: dmg
            file_extension: dmg
          - os: ubuntu-latest
            installer_type: deb
            file_extension: deb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up virtual framebuffer on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Build and Test all modules (Linux)
        if: runner.os == 'Linux'
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn -B verify -Djpackage.skip=true --file pom.xml
      
      - name: Build and Test all modules (Windows/macOS)
        if: runner.os != 'Linux'
        run: mvn -B verify -Djpackage.skip=true --file pom.xml

      - name: Package Application (Linux)
        if: runner.os == 'Linux'
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn -B -pl bybo-app package -DappVersion=${GITHUB_REF_NAME} -DinstallerType=${{ matrix.installer_type }}

      - name: Package Application (Windows/macOS)
        if: runner.os != 'Linux'
        run: mvn -B -pl bybo-app package -DappVersion=${GITHUB_REF_NAME} -DinstallerType=${{ matrix.installer_type }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bybo-${{ runner.os }}
          path: bybo-app/target/dist/*.${{ matrix.file_extension }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      
      - name: List downloaded files
        run: ls -R dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}