# .github/workflows/release.yml

name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0, v2.3.4

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write # Required for softprops/action-gh-release to create a release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      # The github.ref_name variable contains the tag name (e.g., v1.2.3)
      # We pass this to Maven to override the <revision> property in pom.xml
      run: mvn -B clean package "-Drevision=${{ github.ref_name }}" -DskipTests

    - name: Rename MSI Installer for Release
      # The installer is generated as ByBo.msi, so we rename it to include the version
      id: rename_installer
      run: |
        $new_name = "ByBo-Installer-${{ github.ref_name }}.msi"
        $source_path = "bybo-app/target/dist/ByBo.msi"
        Rename-Item -Path $source_path -NewName $new_name
        echo "asset_path=bybo-app/target/dist/$new_name" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Create GitHub Release and Upload Asset
      # This action creates a new GitHub Release and uploads the specified file as an asset
      uses: softprops/action-gh-release@v1
      with:
        # The file to upload. We get the path from the previous step's output.
        files: ${{ steps.rename_installer.outputs.asset_path }}
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
        body: "Automated release for version ${{ github.ref_name }}"
        draft: false
        prerelease: false