# .github/workflows/create-windows-executable.yml

name: Create Windows Installer (MSI)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests

    # ETAPA PRINCIPAL ATUALIZADA
    - name: Package with jpackage into an MSI installer
      run: |
        jpackage `
          --type msi `
          --name "ByBo" `
          --app-version 1.0.0 `
          --vendor "phkaiser13" `
          --input "bybo-app/target/" `
          --main-jar "bybo-app-1.0.0-SNAPSHOT.jar" `
          --main-class "br.com.phkaiser.bybo.app.Launcher" `
          --icon "bybo-app/src/main/resources/br/com/phkaiser/bybo/app/ui/appicons/ByBo.png" `
          --win-menu `
          --win-shortcut

    # ARTEFATO ATUALIZADO
    # Agora faremos o upload do arquivo .msi gerado.
    - name: Upload Windows Installer (MSI)
      uses: actions/upload-artifact@v4
      with:
        name: ByBo-Windows-Installer-MSI
        path: ByBo-1.0.0.msi
